### ISSUE TITLE
preview of vehicles

### ISSUE THREAD

**Issue by salimkayabasi** [mertsimsek/besiege#1]
I think we need to see preview of these vehicles.

Maybe using folders is better for this project

``` bash
/vehicle-1/image.png
/vehicle-1/vehicle-1.bsg
```

**Comment by mertsimsek** [comment]
In this case, Besiege cannot run .bsg files directly. So we must write a script that will update readme on each commit.

**Comment by salimkayabasi** [comment]
[Q] Does Besiege allow using `space` in file name? Like `amansiz savasci`

**Comment by salimkayabasi** [comment]
closing was a mistake

**Comment by mertsimsek** [comment]
[A] Yes, it does.

**Comment by mertsimsek** [comment]
No we are running a script with every push that updates Readme.

[Linkt to the script](https://gist.github.com/mertsimsek/3a604d3245e48bc971c0)
